// <auto-generated />
using System;
using FeeloryBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeeloryBackend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615082434_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SharedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("DayShares", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShareFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DayShareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayShareId");

                    b.HasIndex("ViewerId");

                    b.ToTable("DayShareFeeds", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DaySharePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DayShareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("DayShareId", "DisplayOrder");

                    b.ToTable("DaySharePosts", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShareViewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DayShareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId");

                    b.HasIndex("DayShareId", "ViewerId")
                        .IsUnique();

                    b.ToTable("DayShareViewers", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Emote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Emotes", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.EmotePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.ToTable("EmotePackages", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.EmotePackageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmoteId");

                    b.HasIndex("PackageId", "EmoteId")
                        .IsUnique();

                    b.ToTable("EmotePackageItems", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Friend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique();

                    b.ToTable("Friends", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Friends_CanonicalOrder", "UserId < FriendId");
                        });
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendRequests", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MissionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionTypeId");

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.MissionReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("MissionId", "PackageId")
                        .IsUnique();

                    b.ToTable("MissionRewards", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.MissionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MetricKey")
                        .IsUnique();

                    b.ToTable("MissionTypes", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Type");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MoodEmoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Privacy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MoodEmoteId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.PostFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ViewerId");

                    b.HasIndex("ViewerId", "PostedAt");

                    b.ToTable("PostFeeds", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.PostViewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId");

                    b.HasIndex("PostId", "ViewerId")
                        .IsUnique();

                    b.ToTable("PostViewers", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserLoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("LoginDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoginDate");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginHistories", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RewardClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId", "MissionId")
                        .IsUnique();

                    b.ToTable("UserMissions", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserMissionReactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReactorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReactorId");

                    b.HasIndex("UserId", "MissionId", "PostId", "ReactorId")
                        .IsUnique()
                        .HasFilter("[ReactorId] IS NOT NULL");

                    b.ToTable("UserMissionReactionHistories", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PackageId")
                        .IsUnique();

                    b.ToTable("UserPackages", (string)null);
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShare", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.User", "Owner")
                        .WithMany("DayShares")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShareFeed", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.DayShare", "DayShare")
                        .WithMany("DayShareFeeds")
                        .HasForeignKey("DayShareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayShare");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DaySharePost", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.DayShare", "DayShare")
                        .WithMany("DaySharePosts")
                        .HasForeignKey("DayShareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.Post", "Post")
                        .WithMany("DaySharePosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayShare");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShareViewer", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.DayShare", "DayShare")
                        .WithMany("DayShareViewers")
                        .HasForeignKey("DayShareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "Viewer")
                        .WithMany("DayShareViewers")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayShare");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.EmotePackageItem", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Emote", "Emote")
                        .WithMany("EmotePackageItems")
                        .HasForeignKey("EmoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.EmotePackage", "Package")
                        .WithMany("Items")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emote");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Friend", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.User", "FriendUser")
                        .WithMany("FriendsAsFriend")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("FriendsAsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FriendUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.FriendRequest", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.User", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "Sender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Mission", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.MissionType", "MissionType")
                        .WithMany("Missions")
                        .HasForeignKey("MissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MissionType");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.MissionReward", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Mission", "Mission")
                        .WithMany("Rewards")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.EmotePackage", "Package")
                        .WithMany("MissionRewards")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Notification", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Post", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Emote", "MoodEmote")
                        .WithMany("Posts")
                        .HasForeignKey("MoodEmoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MoodEmote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.PostFeed", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Post", "Post")
                        .WithMany("PostFeeds")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "Viewer")
                        .WithMany("PostFeeds")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.PostViewer", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Post", "Post")
                        .WithMany("PostViewers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "Viewer")
                        .WithMany("PostViewers")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Reaction", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Emote", "Emote")
                        .WithMany("Reactions")
                        .HasForeignKey("EmoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emote");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserLoginHistory", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserMission", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Mission", "Mission")
                        .WithMany("UserMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("UserMissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserMissionReactionHistory", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.Mission", "Mission")
                        .WithMany("ReactionHistories")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.Post", "Post")
                        .WithMany("ReactionMissionHistories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "Reactor")
                        .WithMany("ReactedMissionHistories")
                        .HasForeignKey("ReactorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("MissionReactionHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Post");

                    b.Navigation("Reactor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.UserPackage", b =>
                {
                    b.HasOne("FeeloryBackend.Models.Entities.EmotePackage", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeeloryBackend.Models.Entities.User", "User")
                        .WithMany("UserPackages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.DayShare", b =>
                {
                    b.Navigation("DayShareFeeds");

                    b.Navigation("DaySharePosts");

                    b.Navigation("DayShareViewers");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Emote", b =>
                {
                    b.Navigation("EmotePackageItems");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.EmotePackage", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MissionRewards");

                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Mission", b =>
                {
                    b.Navigation("ReactionHistories");

                    b.Navigation("Rewards");

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.MissionType", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.Post", b =>
                {
                    b.Navigation("DaySharePosts");

                    b.Navigation("PostFeeds");

                    b.Navigation("PostViewers");

                    b.Navigation("ReactionMissionHistories");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("FeeloryBackend.Models.Entities.User", b =>
                {
                    b.Navigation("DayShareViewers");

                    b.Navigation("DayShares");

                    b.Navigation("FriendsAsFriend");

                    b.Navigation("FriendsAsUser");

                    b.Navigation("LoginHistories");

                    b.Navigation("MissionReactionHistories");

                    b.Navigation("Notifications");

                    b.Navigation("PostFeeds");

                    b.Navigation("PostViewers");

                    b.Navigation("Posts");

                    b.Navigation("ReactedMissionHistories");

                    b.Navigation("Reactions");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserMissions");

                    b.Navigation("UserPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
